### ISSUE TITLE
Neo support

### ISSUE THREAD

**Issue by Spinoscythe** [Witixin1512/GeckoLib-MultiLoader-Template#2]
Neo support

**Comment by Witixin1512** [comment]
The original goal of this repository was to showcase how to *attempt* to use GeckoLib, a mod that did not support ML, in an ML environment. This is done by adding the forge dependency in the common project. Of course, this is a bandaid fix.

Given this repository is extremely dated I don't see this being worth it:

- In 1.20.1, NeoForge is very similar to Forge, so much so that everything showcased here will work.
- In 1.20.2 and 1.20.4 my suggestion is to grab the [MultiLoader Template](https://github.com/jaredlll08/MultiLoader-Template/) for that branch and add GeckoLib as shown in this example.
-In 1.20.5 and above, GeckoLib is switching to a MultiLoader setup, which essentially makes this repository become useless. Which is good!
GeckoLib publishes artifacts for common and loader projects. You can find an *example* of this [here](https://github.com/bernie-g/geckolib-examples/tree/Multiloader-1.20.4), although I believe that project is more of a showcase of using GeckoLib, rather than a template / mdk you can start from.

In light of the above, I'm considering archiving this repository as its not very useful anymore.
